# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: SAPstar Network Homelab
# copyright: Copyright &copy; 2022 - 2023 SAPstar Network
repo_url: https://github.com/atraides/homelab
repo_name: atraides/homelab

extra_css:
  - /static/css/asciinema-player.css

extra_javascript:
  - /static/js/asciinema-player.min.js

plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  - git-committers:
      repository: atraides/homelab
      branch: main
  - git-authors

theme:
  name: material

  # Font settings
  font:
    text: "Roboto Condensed"
    code: "Roboto Mono"

  # Reading direction left-to-right
  direction: ltr
  #direction: rtl

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - header.autohide
    - content.code.copy
extra:
  generator: false
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
